[theme]
base = "light"
primaryColor = "#1d4ed8"
backgroundColor = "#ddd8cf"
secondaryBackgroundColor = "#ccc6bc"
textColor = "#1a1714"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
